### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by TomasKostadinov** [filerun/docker#13]
Is there currently an easy way to use the docker image with ssl (e.g. issued by let's encrypt)?
If so, how do I install certificates?

Thanks in advance, loving filerun so far!

**Comment by pirate** [comment]
I just set up a reverse proxy with nginx, but the issue is that filerun still has http hardcoded in many of the urls it requests (which a reverse proxy cant fix easily).

It may be worth adding a docker environment variable like `HTTP_PROTOCOL=https` or `BASE_URL=https://drive.example.com` which gets passed down to fix the broken urls.

**Comment by filerun** [comment]
FileRun does not use urls with hardcoded protocol. Make sure you are using the latest version.

**Comment by filerun** [comment]
If using the latest version and still having this problem, make sure your reverse proxy passes **HTTP_X_FORWARDED_PROTO**, or **HTTP_X_FORWARDED_SSL**, or **HTTP_X_FORWARDED_PORT**. FileRun looks for any of these to determine if the URLs should start using HTTP or HTTPS.

**Comment by scambier** [comment]
If you're on this thread after a Google search, just add this line in your ngix conf file, in the `location` block: `proxy_set_header X-Forwarded-Proto https;`

The 2 other headers **didn't** work for me:
```
proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $scheme;
```

**Comment by Guisardo** [comment]
Thanks @scambier ! It works perfectly. 
@filerun , can you add all this to the Readme?

**Comment by Chrysostomus** [comment]
For some reason this does not work anymore on the later release. `proxy_set_header X-Forwarded-Proto https;` in location block does not seem to work. Http on local network works fine, but when the site is accessed through nginx proxy, it gets stuck in generic loading screen. Either the issue has re-emerged, or there is something wrong with my configuration.

nginx.conf:

```
server {

        root /var/www;
        index index.php index.html index.htm index.nginx-debian.html;

        server_name mysite.fi;

        location / {
                try_files $uri $uri/ =404;
                proxy_pass http://127.0.0.1:8080;
                proxy_redirect      off;
                proxy_set_header    X-Real-IP $remote_addr;
                proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header    X-Forwarded-Host $server_name;
                proxy_set_header    X-Forwarded-Proto https;
                proxy_set_header    X-Forwarded-Port 443;
                proxy_set_header    Host mysite.fi;
        }

        location ~ \.php(?:$|/) {
                include snippets/fastcgi-php.conf;
                fastcgi_pass php;
        }


    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/mysite.fi/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mysite.fi/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


    add_header Strict-Transport-Security "max-age=31536000" always; # managed by Certbot

}
```
I also tried setting the customizeables/config.ini like this:

```
<?php

$config['url']['root'] = 'https://www.chrysocloud.fi/files/';

```
But that does not seem to do anything either. Here is how it looks and its console ouput.

![image](https://user-images.githubusercontent.com/12002226/95166343-61bab380-07b6-11eb-8b2f-f2897ac22d59.png)

When I tried to load the page, the container gives this output:

`web_1  | <IP-Adress> - - [06/Oct/2020:06:31:00 +0000] "GET / HTTP/1.0" 200 1248 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"`

Assuming that this is a configuration issue in nginx, it would be nice to have an example configuration.

**Comment by lmiemus** [comment]
Try adding 
 ```
proxy_redirect http://127.0.0.1:8080 https://$host;
 ```
 to your location / block.

**Comment by coolazeem** [comment]
> The only way would be to install a reverse proxy in front of it (https://www.digitalocean.com/community/tutorials/how-to-secure-haproxy-with-let-s-encrypt-on-ubuntu-14-04#step-3-%E2%80%94-installing-haproxy)
> I am looking into finding an easier solution.

Is there a way to automate this process through the docker-compose file?

**Comment by filerun** [comment]
> Is there a way to automate this process through the docker-compose file?
Try this: https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion

**Comment by coolazeem** [comment]
> > Is there a way to automate this process through the docker-compose file?
> 
> Try this: https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion

Thank you for the link. I was able to get https running with a custom docker-compose.yml combining your official compose file and the proxy companion one.

**Comment by Chrysostomus** [comment]
Would you mind sharing your docker-compose.yml?

**Comment by coolazeem** [comment]
> Would you mind sharing your docker-compose.yml?

Yeah sure - https://bitbucket.org/shaikhazeem/filerun_ssl/

**Comment by PalmaSolutions** [comment]
This issue occurred due to mixed content after switching from LAN IP to hostname via NGINX reverse proxy with Let's Encrypt at NGINX level so I resolved it easily by adding the following to my NGINX reverse proxy config:

```
        proxy_set_header X-Forwarded-Proto $scheme;
        add_header 'Content-Security-Policy' 'upgrade-insecure-requests';
```
Hope it helps as you do not need to modify your docker-compose.yml or go for additional containers or extra configuration.
