### ISSUE TITLE
Dockerfile update

### ISSUE THREAD

**Issue by ytzelf** [filerun/docker#22]
Hi,

I think the Dockerfile is due for an update :)

Thanks a lot!

**Comment by filerun** [comment]
It is indeed :) Working on it...

**Comment by c64bob** [comment]
Any news on this?

**Comment by ytzelf** [comment]
@c64bob would love to know too and have the new skin :)

**Comment by filerun** [comment]
Do note that updating FileRun is not done via Docker. Updating a Docker image will not update the FileRun installation.
FileRun updates are installed from FileRun's control panel: https://docs.filerun.com/updating

**Comment by ytzelf** [comment]
Is this something you're open to reconsider? From what I've seen the actual code is usually handled at the container level while only configuration files are handled through volumes.

**Comment by filerun** [comment]
No.

**Comment by c64bob** [comment]
> 
> 
> Do note that updating FileRun is not done via Docker. Updating a Docker image will not update the FileRun installation.
> FileRun updates are installed from FileRun's control panel: https://docs.filerun.com/updating

Shouldn't a fresh installation with Docker result in a current filerun version? The dockerfile still downloads and installs the previous one (2018.11.11):
https://github.com/filerun/docker/blob/491d03cffb9e75e136b3c83a563107dbd647e9b7/Dockerfile#L46

**Comment by filerun** [comment]
Sure, and that we'll fix. But don't wait for a newer Docker version just to get a newer FileRun version, when you can update the existing install with a few clicks from the FileRun control panel.

**Comment by filerun** [comment]
The Docker image has been now updated for the latest FileRun version (2019.06.01).
