### ISSUE TITLE
Dockerfile for version 2019.06.01 won't update existing installations

### ISSUE THREAD

**Issue by c64bob** [filerun/docker#25]
I have been running filerun version 2018.11.11 using docker. Pulling the new image with version 2019.06.01 and deploying it won't update my existing installation, due to this:

https://github.com/filerun/docker/blob/70b116fd21371dbe909549caf6731107f558ef74/entrypoint.sh#L11

Could you please handle such a scenario?

**Comment by filerun** [comment]
Updating a Docker image will never update FileRun. A Docker container is immutable, serving the single goal of providing FileRun with a preconfigured running environment. A FileRun installation, being a customizable web application is something that you install once and have in your permanent storage. You really don't want a Docker update to mess with your FileRun files.
You can update the FileRun installation at any time from its control panel: https://docs.filerun.com/updating
