### ISSUE TITLE
"Select Users" dialog box not functioning

### ISSUE THREAD

**Issue by pagesix1536** [filerun/docker#26]
When attempting to add users to a shared folder or a group as the superuser, the "Select Users" does not show any users in the list to allow you to chose. Searching for them using the same dialog also shows nothing. There's no way to add any existing users to a group or shared folder. I'm using the docker container version of Filerun composed with the instructions provided.

![Screenshot at 2019-07-12 02-00-24](https://user-images.githubusercontent.com/36011804/61105747-d9315400-a448-11e9-94fb-35ce1c0d12c6.png)

**Comment by filerun** [comment]
The user account you are signed in with, check his "Can interact with" permissions.
