### ISSUE TITLE
Running Filerun docker container as user other than root

### ISSUE THREAD

**Issue by recklessnl** [filerun/docker#27]
Is this possible and if so, how? The majority of Docker containers out there allow you to use environment variables to run it as any user you like. This helps a lot with permission issues.

I don't see anything in the Filerun docker docs about this. Can this be done and if so, how?

**Comment by filerun** [comment]
Yes. Please see the example docker-compose on this page: https://docs.filerun.com/docker

**Comment by kanadaj** [comment]
@filerun The installation process fails if the container is ran as non-root since the process requires `chown` permission

**Comment by klaus1k** [comment]
Is it planned to add the possibility to run the filerun container without root (e.g. with "user: 1000:1000" in docker-compose)?
I'm also getting permission errors because of the chown command.
I think it would benefit security for filerun, especially running as an exposed service.
