### ISSUE TITLE
Docker Install turns up a Blank login Page

### ISSUE THREAD

**Issue by theryecatcher** [filerun/docker#28]
https://github.com/filerun/docker/blob/668c99f62947d8ed8b46264f76f44c808d3c386b/entrypoint.sh#L20

This line seldom to never succeeds creating an empty schema in the new database. On a fresh install I faced this issue leading to an blank login page. This issue was raised by someone else too on [r/FileRun](https://www.reddit.com/r/FileRun/comments/ej7h1y/docker_install_blank_login_screen/).

To resolve that I had to manually import the database after logging into the docker container once it was created. After which it ran without hiccups.

**Comment by filerun** [comment]
Can you please share the contents of your "docker-compose.yml" file?

**Comment by gutyex** [comment]
I think I am also encountering this - no compose.yml file, just two containers set up manually using the settings decribed at https://docs.filerun.com/docker.
The DB has been created in the MariaDB container but contains no tables. 

I get a brief flash of the box in the middle of the page that says 'Loading', then a blank screen. The browser console shows:

Uncaught TypeError: Cannot read property 'length' of null
    at Object.init (login.js?v=:28)
    at login.js?v=:328
    at min.php?extjs=1&v=:2
    at a (min.php?extjs=1&v=:2)

**Comment by ursus-the-bear** [comment]
I have the same problem. Here my docker-compose.yml

```
  filerun_mariadb:
    image: mariadb:10.1
    container_name: filerun_mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_root_pw
      MYSQL_USER: filerun
      MYSQL_PASSWORD: my_secret_pw
      MYSQL_DATABASE: filerun
    volumes:
      - /docker/filerun/db:/var/lib/mysql

  filerun:
    image: afian/filerun
    container_name: filerun
    restart: unless-stopped
    environment:
      FR_DB_HOST: filerun_mariadb
      FR_DB_NAME: filerun
      FR_DB_USER: filerun
      FR_DB_PASS: my_secret_pw
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
    depends_on:
      - filerun_mariadb
    ports:
      - 8080:80
    volumes:
      - /docker/filerun/html:/var/www/html
      - /docker/filerun/user-files:/user-files

**Comment by filerun** [comment]
Tried the above docker-compose on Ubuntu 16, 18, 19, with various Docker versions, and with all the browsers there are. I could not reproduce the problem. Perhaps you have a working URL, where I can at least see the error in your case?

**Comment by ursus-the-bear** [comment]
That's weird. I have Debian 10, newest version. I have the instance up and running, I do not want to open it up to the world because the PW etc. are standard - don't really want to be hacked :) 

I have attached a screenshot, the code that is sent back to the browser and the error message. Does that help?

here is the sceen I get: 

![Screenshot 2020-01-21 at 19 55 23](https://user-images.githubusercontent.com/5219580/72834024-49d2ec00-3c88-11ea-9c95-7d2a9476f58e.png)

this is the error I get in the console:

![Screenshot 2020-01-21 at 19 58 41](https://user-images.githubusercontent.com/5219580/72834175-8f8fb480-3c88-11ea-83ac-b37e6ad831fb.png)

and finaly the code that gets sent to the browser:

```
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
<meta name="application-name" content="FileRun">
<title> :: Login</title>
<link rel="icon" type="image/png" href="data:image/png;base64,iVBORw0KGgo=" />
<link rel="stylesheet" href="css/ext.php?v=&theme=blue" />
<style>
	</style>
</head>
<body id="theBODY">
<div id="loadMsg"><div>Loading...</div></div>

<script src="js/min.php?extjs=1&v="></script>
<script src="js/login.js?v="></script>
<script src="?module=fileman&section=utils&sec=Login%20Page&lang=english&v=&page=translation.js"></script>

<script>
var URLRoot = 'http://192.168.100.200:8080';
var Settings = {"ui_login_title":null,"ui_login_logo":"","ui_login_text":"","ui_bg":null,"ui_bg_color":0,"ui_display_language_menu":false,"androidAppURL":"market:\/\/details?id=com.afian.FileRun","signUpEnabled":0,"ssoEnabled":0,"ssoOnly":0,"passwordRecoveryEnabled":0,"languages":[["english","English","en"]],"selectedLang":"EN","message":false};
var prefilledUsername = '';
var prefilledPassword = '';
var signUpURL = 'http://192.168.100.200:8080/?page=register';
</script>
	<!-- login -->
	<div style="display:block !important;font-size:11px !important;position:fixed !important;bottom:0px !important;right:0px !important;background-color:#EEEEEE !important;border-top-left-radius:2px;color:black !important;padding:3px;z-index:99999 !important;">Website powered by <a href="https://www.filerun.com" style="color:#3079ED !important;font-size:11px !important;" target="_blank">FileRun</a></div>

</body></html>

**Comment by ursus-the-bear** [comment]
oh, I almost forgot. Here is the entry in the log when I access the page: 

first the filerun log: 
```
filerun             | + id -u www-data
filerun             | + '[' '!' -e /var/www/html/index.php ']'
filerun             | + exec apache2-foreground
filerun             | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.20.0.11. Set the 'ServerName' directive globally to suppress this message
filerun             | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.20.0.11. Set the 'ServerName' directive globally to suppress this message
filerun             | [Tue Jan 21 19:27:39.266827 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
filerun             | [Tue Jan 21 19:27:39.290221 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
filerun             | 192.168.1.2 - - [21/Jan/2020:19:28:03 +0000] "GET / HTTP/1.1" 200 1268 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Safari/605.1.15"
```

and then the mariadb logs:

```
filerun_mariadb     | 2020-01-21 19:27:32+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.1.43+maria-1~bionic started.
filerun_mariadb     | 2020-01-21 19:27:35+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
filerun_mariadb     | 2020-01-21 19:27:35+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.1.43+maria-1~bionic started.
filerun_mariadb     | 2020-01-21 19:27:36 140305707096064 [Note] mysqld (mysqld 10.1.43-MariaDB-1~bionic) starting as process 1 ...
filerun_mariadb     | 2020-01-21 19:27:37 140305707096064 [Note] InnoDB: Using mutexes to ref count buffer pool pages
filerun_mariadb     | 2020-01-21 19:27:37 140305707096064 [Note] InnoDB: The InnoDB memory heap is disabled
filerun_mariadb     | 2020-01-21 19:27:37 140305707096064 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
filerun_mariadb     | 2020-01-21 19:27:37 140305707096064 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
filerun_mariadb     | 2020-01-21 19:27:37 140305707096064 [Note] InnoDB: Compressed tables use zlib 1.2.11
filerun_mariadb     | 2020-01-21 19:27:37 140305707096064 [Note] InnoDB: Using Linux native AIO
filerun_mariadb     | 2020-01-21 19:27:37 140305707096064 [Note] InnoDB: Using SSE crc32 instructions
filerun_mariadb     | 2020-01-21 19:27:37 140305707096064 [Note] InnoDB: Initializing buffer pool, size = 256.0M
filerun_mariadb     | 2020-01-21 19:27:37 140305707096064 [Note] InnoDB: Completed initialization of buffer pool
filerun_mariadb     | 2020-01-21 19:27:37 140305707096064 [Note] InnoDB: Highest supported file format is Barracuda.
filerun_mariadb     | 2020-01-21 19:27:37 140305707096064 [Note] InnoDB: 128 rollback segment(s) are active.
filerun_mariadb     | 2020-01-21 19:27:37 140305707096064 [Note] InnoDB: Waiting for purge to start
filerun_mariadb     | 2020-01-21 19:27:37 140305707096064 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.45-86.1 started; log sequence number 21077926
filerun_mariadb     | 2020-01-21 19:27:37 140305707096064 [Note] Plugin 'FEEDBACK' is disabled.
filerun_mariadb     | 2020-01-21 19:27:37 140304753616640 [Note] InnoDB: Dumping buffer pool(s) not yet started
filerun_mariadb     | 2020-01-21 19:27:37 140305707096064 [Note] Server socket created on IP: '::'.
filerun_mariadb     | 2020-01-21 19:27:37 140305707096064 [Warning] 'proxies_priv' entry '@% root@45b23ddd2235' ignored in --skip-name-resolve mode.
filerun_mariadb     | 2020-01-21 19:27:37 140305707096064 [Note] mysqld: ready for connections.
filerun_mariadb     | Version: '10.1.43-MariaDB-1~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution

```
 hope that helps

**Comment by filerun** [comment]
A fresh Debian 10 instance, just installed docker, docker-compose, and ran the above yml file, with the FileRun login showing fine.

Are you seeing this line in your log?

`filerun            | wait-for-it.sh: filerun_mariadb:3306 is available after 24 seconds`

**Comment by ursus-the-bear** [comment]
yes, I did get that on the first run, although it said waiting for 120 (or 200) secs...

**Comment by ursus-the-bear** [comment]
I have about 6 containers running - there are two more maria db instances running, is filerun maybe getting confused with the other maria db's?

**Comment by ursus-the-bear** [comment]
attached please find my .YML file (replaced sensitive info with xxx). Maybe one of the other containers are the problem?

[docker-compose.txt](https://github.com/filerun/docker/files/4093417/docker-compose.txt)

**Comment by ursus-the-bear** [comment]
I did a complete reinstall (just to be sure I got the wait-for-it message):

```
filerun             | + cp /autoconfig.php /var/www/html/system/data/
filerun             | + chown -R www-data:www-data /var/www/html
filerun             | + chown www-data:www-data /user-files
filerun             | + mysql_host=filerun_mariadb
filerun             | + mysql_port=3306
filerun             | + /wait-for-it.sh filerun_mariadb:3306 -t 120 -- /import-db.sh
filerun             | wait-for-it.sh: waiting 120 seconds for filerun_mariadb:3306
```

these are the last entries in the maria_db log:
```
filerun_mariadb     | 2020-01-24  9:00:30 140318265235456 [Warning] 'user' entry 'root@87e35544d042' ignored in --skip-name-resolve mode.
filerun_mariadb     | 2020-01-24  9:00:30 140318265235456 [Warning] 'proxies_priv' entry '@% root@87e35544d042' ignored in --skip-name-resolve mode.
filerun_mariadb     | 2020-01-24  9:00:30 140318265235456 [Note] mysqld: ready for connections.
filerun_mariadb     | Version: '10.1.43-MariaDB-1~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  mariadb.org binary distribution
filerun_mariadb     | 2020-01-24 09:00:31+00:00 [Note] [Entrypoint]: Temporary server started.
filerun_mariadb     | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
```

finally, I then got a timeout:
```
filerun             | ERROR 2003 (HY000): Can't connect to MySQL server on 'filerun_mariadb' (111 "Connection refused")
```

I then installed phpMyAdmin and it seems as if filerun installs the database, but then cannot access it:

![Screenshot 2020-01-24 at 10 09 24](https://user-images.githubusercontent.com/5219580/73057544-0fd53600-3e92-11ea-8733-edeade9feb22.png)

If I then open the filerun database there are no tables etc. 

Any idea how I can fix this?

**Comment by theryecatcher** [comment]
Sorry got a bit busy, will test on a new setup today and try to recreate the original issue I faced. But yeah I never saw the lines 
```
filerun | wait-for-it.sh: filerun_mariadb:3306 is available after 24 seconds
```
in the creation log.

**Comment by theryecatcher** [comment]
With the original docker-compose.yml
```
web_1  |    creating: /var/www/html/oauth2/authorize/nextcloud_flow_v2_done/
web_1  |   inflating: /var/www/html/oauth2/authorize/nextcloud_flow_v2_done/index.php  
web_1  |   inflating: /var/www/html/oauth2/index.php  
web_1  |    creating: /var/www/html/oauth2/token/
web_1  |   inflating: /var/www/html/oauth2/token/index.php  
web_1  |    creating: /var/www/html/oauth2/token/info/
web_1  |   inflating: /var/www/html/oauth2/token/info/index.php  
web_1  |    creating: /var/www/html/ocs/
web_1  |   inflating: /var/www/html/ocs/v1.php  
web_1  |   inflating: /var/www/html/ocs/v2.php  
web_1  |    creating: /var/www/html/oembed/
web_1  |   inflating: /var/www/html/oembed/index.php  
docker_web_1 exited with code 1
```

diff docker-compose.yml
```
iff --git a/docker-compose.yml b/docker-compose.yml
index b299bff..a4a7fec 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -4,21 +4,21 @@ services:
   db:
     image: mariadb:10.1
     environment:
-      MYSQL_ROOT_PASSWORD: your_mysql_root_password
-      MYSQL_USER: your_filerun_username
-      MYSQL_PASSWORD: your_filerun_password
-      MYSQL_DATABASE: your_filerun_database
+      MYSQL_ROOT_PASSWORD: passwd
+      MYSQL_USER: grumpy
+      MYSQL_PASSWORD: captcha
+      MYSQL_DATABASE: filerun
     volumes:
-      - /filerun/db:/var/lib/mysql
+      - mariadb:/var/lib/mysql
 
   web:
     image: afian/filerun
     environment:
       FR_DB_HOST: db
       FR_DB_PORT: 3306
-      FR_DB_NAME: your_filerun_database
-      FR_DB_USER: your_filerun_username
-      FR_DB_PASS: your_filerun_password
+      FR_DB_NAME: filerun
+      FR_DB_USER: grumpy
+      FR_DB_PASS: captcha
       APACHE_RUN_USER: www-data
       APACHE_RUN_USER_ID: 33
       APACHE_RUN_GROUP: www-data
@@ -28,7 +28,10 @@ services:
     links:
       - db:db
     ports:
-      - "80:80"
+      - "9080:80"
     volumes:
-      - /filerun/html:/var/www/html
-      - /filerun/user-files:/user-files
+      - ../filerun/html:/var/www/html
+      - ../filerun/user-files:/user-files
+
+volumes:
+  mariadb:
```

**Comment by ursus-the-bear** [comment]
I fixed my problem but deactivating the other containers I had in the docker-compose file, deleted the files that where created on the first run and then started just the 2 containers. I then stoped the containers and restarted ALL the containers. It seems as if filerun cannot figure out which mariadb container it needs to connect to.

**Comment by Makeshift** [comment]
After following the instructions on the docs page I had the exact same issue. Then after deleting the `db`, `html` and `user-files` folders and allowing them to regenerate, it worked fine.

I suspect this may be caused by the *first run* configuration being incorrect, eg. the db being down/inaccessible the first time you run the filerun container. Any subsequent runs will then fail.

This is due to this line in entrypoint: https://github.com/filerun/docker/blob/master/entrypoint.sh#L12
On a fresh install, `index.php` is extracted, and only right at the end of that code block does the db import take place. If the db import fails for any reason it won't then try again on subsequent startups because index.php is there.

I would advise moving the `import-db` step to the top of that code block, then if it fails it will attempt again on next run.

**Comment by ursus-the-bear** [comment]
@Makeshift thank you for the update. I fixed it by removing my other dockers but that might have been a false positive! keep healthy!

**Comment by pharmarin** [comment]
Had the same issue when putting whitespaces in my mariadb password. Removed the blanks and now import-db.sh succeeds.

**Comment by veneris** [comment]
I ran into the same problem using docker.  
This is the error message from the console:  
```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self' http: https: data: blob: 'unsafe-inline'".
    at min.php?extjs=1&v=2020.11.21:formatted:1857
    at min.php?extjs=1&v=2020.11.21:formatted:2085
(anonymous) @ min.php?extjs=1&v=2020.11.21:formatted:1857
(anonymous) @ min.php?extjs=1&v=2020.11.21:formatted:2085

Uncaught TypeError: Ext.onReady is not a function
    at login.js?v=2020.11.21:327
```
I have no problem using ip and port number to access, but there is a problem using domain name.

**Comment by veneris** [comment]
> I ran into the same problem using docker.
> This is the error message from the console:
> 
> ```
> Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self' http: https: data: blob: 'unsafe-inline'".
>     at min.php?extjs=1&v=2020.11.21:formatted:1857
>     at min.php?extjs=1&v=2020.11.21:formatted:2085
> (anonymous) @ min.php?extjs=1&v=2020.11.21:formatted:1857
> (anonymous) @ min.php?extjs=1&v=2020.11.21:formatted:2085
> 
> Uncaught TypeError: Ext.onReady is not a function
>     at login.js?v=2020.11.21:327
> ```
> 
> I have no problem using ip and port number to access, but there is a problem using domain name.

I think I have found the problem. The problem lies in the security configuration of nginx. It will be fine after I delete it.

**Comment by Joly0** [comment]
Hey, i am having a similar issue now aswell on my filerun instance. I installed it via docker (manually on unraid, not through docker-compose) and it worked perfectly until recently (i suspect since the latest update of this container).

I cant reach the webinterface and only get error 500 and a blank page (though the filerun icon for the browser tab loads, weirdly). It seems like webdav is working, its just the webinterface.

Is there anythin i can do now to solve this issue, is urgent..

Thank you in advance :)

**Comment by Joly0** [comment]
Ok btw, i figured the root of the problem i had. After updating the docker container (why ever) the language files (in my case german) got deleted and only english (which is the default) remained. And as i have configured filerun to use german as the default language and as it was unable to find the file, i couldnt access the webpage with any other account other then my own, as i have set english as the default language for my account (atleast thats what my testing showed me)
This shouldnt happen imho and it should get tested.
