### ISSUE TITLE
Configure "trash" path via an environment variable

### ISSUE THREAD

**Issue by nilp0inter** [filerun/docker#35]
I am unable to delete any files. I am getting the following error:

![image](https://user-images.githubusercontent.com/1224006/103563023-5b72cb00-4ebc-11eb-862e-88ac0d973fc4.png)

I suspect this is due the path of the trash folder not being correctly configured. I'd like to configure it via an environment variable if possible.

**Comment by filerun** [comment]
The trash folder location can be set from the configuration file. Search for "$config['path']['trash']" on this page: https://docs.filerun.com/advanced_configuration
