### ISSUE TITLE
Define password and username as environment

### ISSUE THREAD

**Issue by Whisper40** [filerun/docker#36]
This project does not use a lot of env variable for being configured. I think it's a good thing to let as much as possible options to users. Please consider adding env variable for basic things such as username and password in order to do not have to modify them in interface..

Because anybody who connects before us on the page can connect without problem..

Thanks

**Comment by filerun** [comment]
Credentials are better stored encrypted in FileRun's own database.

**Comment by Whisper40** [comment]
Sure, but it needs a human operation..

**Comment by filerun** [comment]
Perhaps I misunderstood. This defined password would be just used as default at installation time, instead of the randomly generated one?

**Comment by Whisper40** [comment]
Yes exactly, a default username and a default password that can be ready to use to configure the setup instead of using a specific username and specific password that you have hardcoded
