### ISSUE TITLE
graphicsmagick missing

### ISSUE THREAD

**Issue by c64bob** [filerun/docker#39]
I think graphicsmagick is missing. There is no /usr/bin/gm present, and thumbnail creating fails. When manually installing graphicsmagick, thumbnail creation works.

**Comment by filerun** [comment]
New Docker image ready: https://hub.docker.com/r/filerun/filerun
Upgraded FileRun to version 2021.12.07, added libvips, HEIC support, latest ImageMagick version with support for RAW photos, Libreoffice, pngquant, enabled stl-thumb by default.

Note that pulling a new Docker image will never update a FileRun installation. FileRun updates are installed only from the FileRun control panel section "Update" (https://docs.filerun.com/updating)

**Comment by schester44** [comment]
what about containers that do not have an outbound network connection?
