### ISSUE TITLE
E: Unable to locate package ufraw

### ISSUE THREAD

**Issue by Mist-Hunter** [filerun/docker#41]
While building locally, I'm getting this:
```E: Unable to locate package ufraw```

https://askubuntu.com/questions/1241812/how-can-i-get-ufraw-in-ubuntu-20-04

May not be important, but sharing in case it is.

**Comment by filerun** [comment]
Thank you for pointing it out!
New Docker image ready: https://hub.docker.com/r/filerun/filerun
Upgraded FileRun to version 2021.12.07, added libvips, HEIC support, latest ImageMagick version with support for RAW photos, Libreoffice, pngquant, enabled stl-thumb by default.
