### ISSUE TITLE
Outdated version still on docker hub

### ISSUE THREAD

**Issue by detlefs** [filerun/docker#43]
The version available on docker hub as "latest" is 4 months old. Could it please be updated to the newer version 2021.06.27?

**Comment by filerun** [comment]
New Docker image ready: https://hub.docker.com/r/filerun/filerun
Upgraded FileRun to version 2021.12.07, added libvips, HEIC support, latest ImageMagick version with support for RAW photos, Libreoffice, pngquant, enabled stl-thumb by default.

Note that pulling a new Docker image will never update a FileRun installation. FileRun updates are installed only from the FileRun control panel section "Update" (https://docs.filerun.com/updating)
