### ISSUE TITLE
add user / update password in command line ?

### ISSUE THREAD

**Issue by changchichung** [filerun/docker#44]
Does filerun support add user / update user password from command line ?
there's no such command in https://docs.filerun.com/command_line_tools to do the job.

But I a similar command reset_superuser_pass.php , since superuser's password can be reset.
maybe this file can be modified to update user's password ?

or just update password field in the database ?

**Comment by filerun** [comment]
Users can be added and their settings can changed only via the FileRun control panel or the API (https://docs.filerun.com/api#modify_filerun_user_accounts)
