### ISSUE TITLE
Creating filerun_db_1 ... error

### ISSUE THREAD

**Issue by lukaspavelka** [filerun/docker#45]
Hello today build, cloned from git but still: 

root@home-sa:/home/docker/filerun# docker-compose up -d
Creating network "filerun_default" with the default driver
Pulling db (mariadb:10.1)...
10.1: Pulling from library/mariadb
01bf7da0a88c: Pull complete
f3b4a5f15c7a: Pull complete
57ffbe87baa1: Pull complete
7ac3ea3a19e9: Pull complete
b89d9d23853d: Pull complete
6512bf94537d: Pull complete
d75afd385b71: Pull complete
ab1935952eac: Pull complete
209bb6034896: Pull complete
aa325c613ddb: Pull complete
050a67aa09df: Pull complete
bdb7d28d54b6: Pull complete
0bc74f023b50: Pull complete
Digest: sha256:1205b21b713812a6ba9fb59df206017dc06976fe68e172fbc6d153d7a4e13dfe
Status: Downloaded newer image for mariadb:10.1
Pulling web (afian/filerun:)...
latest: Pulling from afian/filerun
b4d181a07f80: Pull complete
78b85dd8f014: Pull complete
8589b26a90be: Pull complete
f5af5d641946: Pull complete
614ec6f0b8d6: Pull complete
12b28f3797fb: Pull complete
96bcb7d2e6b0: Pull complete
fdb99f417e70: Pull complete
54591be7a3e1: Pull complete
e482b4aefb55: Pull complete
d331703849ca: Pull complete
bc5a699772c0: Pull complete
f9a69349a09a: Pull complete
2ec710521467: Pull complete
5d39a50a79ee: Pull complete
2d858e7e0f65: Pull complete
716b4992da89: Pull complete
Digest: sha256:c229d3b5d264a0f319a4f4e6e1feb0898deda49590f9d6d95eefadb4b0cbb45d
Status: Downloaded newer image for afian/filerun:latest
Creating filerun_db_1 ... error

ERROR: for filerun_db_1  Cannot start service db: error while creating mount source path '/filerun/db': mkdir /filerun: read-only file system

ERROR: for db  Cannot start service db: error while creating mount source path '/filerun/db': mkdir /filerun: read-only file system
ERROR: Encountered errors while bringing up the project.

**Comment by lukaspavelka** [comment]
any idea what to do ?

**Comment by filerun** [comment]
Adjusting permissions of the folder /filerun should fix this.
