### ISSUE TITLE
API greyed out

### ISSUE THREAD

**Issue by pbengert** [filerun/docker#47]
Starting the docker image with the provided docker-compose file (https://docs.filerun.com/docker) works fine except that the "Enable API" option under control-panel --> security --> API is greyed out.
It's the same if I use unencrypted html (via IP and port) or if I use it behind a caddy proxy with tls/https.
My understanding is that you should be able - at least for testing purpose - to allow api via unecrypted html.

**Comment by filerun** [comment]
There is no code that would gray out that option, so there must be something else going on. Please provide a screenshot.
This is what I see on a default installation via Docker:
![image](https://user-images.githubusercontent.com/6422152/146896130-a00120b0-ced9-4666-956f-519a68d455fc.png)
I can enable the options just fine.

**Comment by pbengert** [comment]
I attached the screenshot but I think the problem is solved. There seems to be a problem with the Safari Browser on MacOS (MacOS Ver 12.1, Safari 15.2). The "Enable API" button is not clickable.

<img width="374" alt="CleanShot 2021-12-21 at 13 00 16@2x" src="https://user-images.githubusercontent.com/24936330/146926617-fe172be7-e025-45af-924f-bc119480878c.png">

But if I switch to Chrome or Firefox the API Button can be enabled. So it seems to be some problem with the button only on Safari. Happy to provide more information if needed. But as the workaround is just to use an other browser I'll close the issue. Thank you!
