### ISSUE TITLE
Cannot Access Control Panel with Nginx

### ISSUE THREAD

**Issue by g0d-m0nky** [filerun/docker#49]
FileRun itself is running wonderfully. When I access it through localhost:port everything works well including the control panel. I have now mapped it through SWAG and while https://filerun.domain works, if I try to access the control panel (https://filerun.domain/?module=cpanel#/cpanel/security) I get 
```
This page isn’t working
filerun.domain is currently unable to handle this request.
HTTP ERROR 500
```

This is my SWAG config file

```
server {

    listen 443 ssl;
    listen [::]:443 ssl;

    server_name filerun.*;

    include /config/nginx/ssl.conf;
    include /config/nginx/internal.conf;
    client_max_body_size 0;


location / {
    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;
    set $upstream_app filerun;
    set $upstream_port 80;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    proxy_set_header X-Forwarded-Proto https;
    }
}
```

**Comment by filerun** [comment]
Sorry for the late reply, I mostly handle issues via [https://feedback.filerun.com](https://feedback.filerun.com)
The following should help:
`set $upstream_proto https;`

**Comment by filerun** [comment]
The problem was related to Nginx Proxy Manager, the discussion and the fix can be found here: https://feedback.filerun.com/en/communities/1/topics/1364-nginx-proxy-manager-wan-access-lan-access
