### ISSUE TITLE
Allow external database and non default information

### ISSUE THREAD

**Issue by DracoMilesX** [filerun/docker#5]
It would be great if instead of a docker-compose database with default username/password we could get environment tags where we can define db host/port/user/pass for people that all ready have an database instance.

**Comment by bilyboy785** [comment]
yes .. it could be better, because for now it doesnt work ...

**Comment by roelofjansen** [comment]
I am trying to deploy on kubernetes but not working this way.

**Comment by filerun** [comment]
Support for custom database connection details has been now added.
