### ISSUE TITLE
Docker image versioning

### ISSUE THREAD

**Issue by thevops** [filerun/docker#54]
For now, there is no option to install specific version of Filerun. Every time we start container, it downloads and installs latest version. I think, it's not good.

Is there any possibility to download specific Filerun version?

**Comment by filerun** [comment]
Maybe not ideal, but it minimizez the amount of work I have to do, so for now it's going to be like this.
Enterprise FileRun license owners can contact us for older FileRun versions.

**Comment by githubsaturn** [comment]
Hi @filerun  - this is sort of defeats the purpose of immutability and repeatability of using Docker images. Say you introduce a breaking change in a future version that requires other env vars etc, all instances suddenly stop working without people knowing what's going on. 

It's a small investment, but it's gonna save you time and headache down the road.
