### ISSUE TITLE
How to skip installation step 

### ISSUE THREAD

**Issue by DarkDeddok** [filerun/docker#58]
Help me pls, I need to skip this step and open the login page? are there any solutions? maybe mount configuration file in docker-compose or any queries to the database?

**Comment by filerun** [comment]
How can install something by skipping the installation? And why?

**Comment by filerun** [comment]
Tell me about this platform, as the license of the free FileRun version prohibits such usage.

**Comment by filerun** [comment]
For further information, you are welcome to talk to us: info@filerun.com

**Comment by DarkDeddok** [comment]
I have a platform through which I plan to deploy a separate filerun for each department in my company

**Comment by filerun** [comment]
You are allowed to use one single FileRun instance. Kindly do not push us to remove commercial usage altogheter from the free FileRun version.

**Comment by DarkDeddok** [comment]
ok i will look for an alternative
