### ISSUE TITLE
群晖docker只能用命令行运行，在网页端设置出现8081端口拒绝访问错误

### ISSUE THREAD

**Issue by tefiszx** [filerun/docker#6]
我在群晖nas上安装了这个docker。安装命令如下
docker run --name=aira2 -v /volume1/aria2/:/var/www/html/system/data/default_home_folder  -dti -p 8081:80 -p 6800:6800 jaegerdocker/pan

安装正常无出错。进入群晖nas的网页端，打开docker组件，里面显示运行正常。

然而在nas的网页端进行设置。则会出现8081端口拒绝连接的情况。查看dockr的日志显示一切正常，无出错提示。但是网页访问http://myNASip:8081 出现无法访问的错误。于是进入nas的控制台，用crul 127.0.0.1:8081检测端口。提示连接refused。这是群晖的原因还是docker的原因？

**Comment by filerun** [comment]
#7
