### ISSUE TITLE
Image needs to be rebuilt and pushed to docker hub

### ISSUE THREAD

**Issue by zmweske** [filerun/docker#65]
Hi, https://hub.docker.com/r/filerun/filerun hasn't been updated in a year even though there have been more recent updates to filerun itself. When pulling the most recent image, it uses the filerun version from over a year ago. 

My understanding is that this image needs to be rebuilt and then re-pushed to the docker hub. 

To test this, you can pull the image and spin up an instance. Going into Control Panel -> Update and checking for updates will tell you if things are working better.

**Comment by filerun** [comment]
This is not accurate, it will always install the latest FileRun version. FileRun is not shipped with the Docker image.
