### ISSUE TITLE
Limitation on the number of users for the free version

### ISSUE THREAD

**Issue by luke6464** [filerun/docker#69]
First of all congratulations for the project, I think it's one of the best file browsers out there! ... pity that the policy of limiting the number of user accounts for the free version is too penalizing for this application. I feel like giving some advice to the author ...
I believe that limiting user accounts through licenses is too penalizing for the chances that this app would have to expand and be number 1 ...
I personally tried it as a private individual and I am I was very satisfied with the features offered but unfortunately due to the limitation on the number of users I had to abandon it to switch to other projects such as NexCloud ... too bad! ... because if there weren't that limitation on the license it would become the first application of its kind in the world.
For projects like this, it doesn't make much sense for private users to pay for the Enterprise license just to increase the number of user accounts they can set up. I agree with limiting some "corporate" features but I think it's too penalizing for individuals who want a non-profit file browser and therefore can't afford to pay. I hope that the author in the future decides to change the licensing policy and allow this fantastic application to expand and be known even more.
Thanks and congratulations.

**Comment by filerun** [comment]
Thank you for your message and feedback.
The average family size in the world has 4.9 people. The free FileRun version allows for 10 users.
For non-profit organizations or similar larger groups, they can request an increase of number of users for free for they particular case, and I usually provide it. If your particular family is large, and they would actually use FileRun, you are welcome to send me a family tree with their names, and I will accomodate ;)
Being number one would feed my ego but not my family.

**Comment by luke6464** [comment]
I fully understand the need to feed your family with your work and in fact my note did not want to be against the payment of the product but mine was only a consideration on the business model of licenses linked to the number of accounts! ... in most software products the licenses always provide for a diversified policy with respect to advanced features such as corporate ones related to security while for non-profit projects certain features can even be negligible. In fact, there are projects like my personal non-profit where as a school teacher I need to share hundreds of school-type files and documents for free with an "indefinite" number of students that we cannot know in advance and we could never manage . For many realities like these, limiting software with the number of user accounts automatically excludes it from a large slice of the market including business activities where one would also like to pay for the license but it is absurd to link it to the number of users (perhaps it would make more sense to link it to number of servers on which the product is installed) ... obviously mine are considerations relating only to the commercial model, which in my opinion if changed could make this product more interesting also for many other companies willing to pay for it but with respect to the features that offers and not with respect to the number of users it can register.
Thanks anyway for the pleasant exchange of views and I hope that this product can achieve the greatest success it deserves. ;)
