### ISSUE TITLE
Login progress..... 

### ISSUE THREAD

**Issue by bilyboy785** [filerun/docker#7]
Using docker, i can't login to the webUI with superuser : 
I've got a screen but nothing else ..

![](https://dsc.cloud/martinbouillaud/Screen-Shot-2017-11-22-10-06-30/Screen-Shot-2017-11-22-10-06-30.png)

I've got that in console : 
```
Mixed Content: The page at 'https://dl.netfloux.com/?language=french' was loaded over HTTPS, but requested an insecure form action 'http://dl.netfloux.com/?module=fileman&page=login&action=login'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by kennethklee** [comment]
Hit this as well. Appears as though http is hardcoded; I couldn't serve filerun over https.

**Comment by filerun** [comment]
Detection for reverse proxy with different ports or protocol (HTTPS) will be included with the upcoming update.
