### ISSUE TITLE
can not build filerun on centos 7

### ISSUE THREAD

**Issue by yyqyu** [filerun/docker#9]
always errors as follow：

PHP configuration: open_basedir | /www/wwwroot/file.occ.ac.cn/:/tmp/:/proc/ | PHP's file access is restricted to these defined directories!
-- | -- | --

and there the button（doc/file）is blocked
whats wrong with it

**Comment by filerun** [comment]
You say you cannot "build", while showing an error from the web-based installer, which would not prevent you from completing the install.

**Comment by filerun** [comment]
closed for lack of clarification
